# ICT PLATFORM
# Build your Angular project and run tests with Karma.
# Author: Hoangl

trigger:
  branches:
    include:
    - dev
    - staging
    - releases/*
    exclude:
    - releases/old*

pool:
  name: AgentPool

variables:
- group: k8s-ci-variable
#- name: TAG
#  value: '$(Build.SourceVersion)'

steps:
#- task: npmAuthenticate@0
#  displayName: 'npm Authenticate .npmrc'
#  inputs:
#    workingFile: .npmrc
#    customEndpoint: 'GitHub Registry'
- task: Docker@2
  displayName: Login to registry.evn.com.vn
  inputs:
    command: login
    containerRegistry: HarbourRegistryConnection1
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(ENV)/$(IMAGE)
    containerRegistry: HarbourRegistryConnection1
    tags: $(TAG)

#- script: 'docker build -t $(REGISTRY)/$(ENV)/$(IMAGE):$(TAG) .'
#  displayName: 'Build Image'

#- script: 'docker push $(REGISTRY)/$(ENV)/$(IMAGE):$(TAG)'
#  displayName: 'Push Image'

#- script: 'docker image rm $(REGISTRY)/$(ENV)/$(IMAGE):$(TAG)'
#  displayName: 'Remove Image'

- script: |
   docker run --env-file $(K8S_CI_ENV) $(REGISTRY)/$(ENV)/k8s-ci:latest yarn start patch $(Build.SourceVersion) $(ENV)/$(WORKLOAD_FILE)
   git clone --single-branch --branch $(WORKLOAD_BRANCH) $(WORKLOAD_REPO) $(Build.BuildNumber)
   kubectl apply -f "$(Build.BuildNumber)/$(ENV)/$(WORKLOAD_FILE)"
   rm -rf $(Build.BuildNumber)
  displayName: 'Apply to K8S Cluster'

