import { Component, ElementRef, OnDestroy, OnInit, ViewChild, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription, takeUntil, timeout, Subject } from 'rxjs';
import { AbstractControl, FormArray, FormBuilder, FormGroup, RequiredValidator, UntypedFormBuilder, UntypedFormGroup, Validators } from '@angular/forms';
import { MessageService } from 'app/shared/message.services';
import { SnotifyToast } from 'ng-alt-snotify';
import { State } from 'app/shared/commons/conmon.types';
import { BaseDetailInterface } from 'app/shared/commons/basedetail.interface';
import { UserService } from 'app/core/user/user.service';
import { BaseComponent } from 'app/shared/commons/base.component';
import { FunctionService } from 'app/core/function/function.service';
import { ListdinhhuongService } from '../listdinhhuong.service';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { ServiceService } from 'app/shared/service/service.service';
import { MatDialog } from '@angular/material/dialog';
import { PopupFileComponent } from 'app/shared/component/popup-file/popup-filecomponent';
import { PopupCbkhComponent } from './popup-cbkh/popup-cbkh.component';
import { User } from 'app/core/user/user.types';
import { DOfficeService } from 'app/shared/service/doffice.service'
import { DOfficeComponent } from 'app/shared/component/d-office/d-office.component';
import { ViewFileComponent } from 'app/shared/component/view-file/view-file.component';

@Component({
    selector: 'component-details',
    templateUrl: './details.component.html',
    styleUrls: ['./details.component.css'],
    encapsulation: ViewEncapsulation.None,
})

export class ApiDinhHuongDetailsComponent implements OnInit {

    public selectedYear: number;
    public selectedStatus: string;
    public actionClick: string = null;
    public getYearSubscription: Subscription;
    public getStatusSubscription: Subscription;
    public listYears = [];
    public listStatus = [];
    public showTable = true
    public form;
    public dataImport = {
        arr: []
    }
    @ViewChild('fileUpload2') fileUpload2: ElementRef;
    public idParam: string = null;
    public checkChiTiet: string = null;
    public listDonvi = [];
    public listChiTietImport = [];
    submitted = { check: false };
    public listFile;
    public listFileDelete = [];
    public actionType: string = null;
    public makehoach: string = null;
    public screen;
    public checkDOffice = false;
    public linkDoffice = "";
    user: User;
    private _unsubscribeAll: Subject<any> = new Subject<any>();
    constructor(
        private _formBuilder: FormBuilder,
        public _activatedRoute: ActivatedRoute,
        public _router: Router,
        private _serviceApi: ServiceService,
        public _messageService: MessageService,
        public dialog: MatDialog,
        private _userService: UserService,
        private _dOfficeApi: DOfficeService,
    ) {
        this.idParam = this._activatedRoute.snapshot.paramMap.get('id');
        this._activatedRoute.queryParams.subscribe(params => {
            this.checkChiTiet = params["type"];
            this.updateKeHoach();
            if (params?.type) {
                this.actionType = params?.type;
            } else {
                this.actionType = null;
            }
            if (params?.screen) {
                this.screen = params?.screen;
            }
            if (params?.makehoach) {
                this.makehoach = params?.makehoach;
            } else {
                this.makehoach = null;
            }
            this.initForm()
            if (this.actionType == "THEMMOI") {
                this._serviceApi.dataKeHoach.next({capTao:'DONVI'});
                this.getCheckQuyenDoffice();

            }else if(this.actionType == "CHINHSUA"){
                this.getCheckQuyenDoffice();
            }
        }
        )

    }


    ngOnInit() {
        this.geListYears()
        // this.getListStatus()
        this.geListNhomDonVi();
        this.selectedYear = (new Date()).getFullYear();
        // console.log(this.form.value);
        this.getCheckQuyenDoffice()

    }

    
    getCheckQuyenDoffice() {
        this._userService.user$
            .pipe(takeUntil(this._unsubscribeAll))
            .subscribe((user: any) => {
                this.user = user;
                this._serviceApi.execServiceLogin("3FADE0E4-B2C2-4D9D-A0C7-06817ADE4FA3", [{ "name": "ORGID", "value": user.ORGID }]).subscribe((data) => {
                    if (data.data.API_DOFFICE) {
                        this.checkDOffice = true;
                        this.linkDoffice = data.data.API_DOFFICE;
                    }
                })
            });

    }

    geListNhomDonVi() {
        this._serviceApi.execServiceLogin("030A9A96-90D5-4AD0-80E4-C596AED63EE7", null).subscribe((data) => {
            this.listDonvi = data.data || [];
        })
    }

    initForm() {
        // if(this.idParam != undefined && this.idParam !=''){
        //     this.getYearSubscription = this._serviceApi.execServiceLogin("B73269B8-55CF-487C-9BB4-99CB7BC7E95F", [{"name":"MA_KE_HOACH","value":this.idParam}]).subscribe((data) => {
        //         this.form = this._formBuilder.group({
        //             name: [data.data.TEN_KE_HOACH, [Validators.required]],
        //             year: [data.data.NAM, [Validators.required]],
        //             maKeHoach:this.idParam
        //         }
        //         )
        //     })

        // }else{
        this.form = this._formBuilder.group({
            name: [null, [Validators.required]],
            year: [(new Date()).getFullYear(), [Validators.required]],
            maKeHoach: this.idParam,
            listChiTietImport: [],
            
        }
        )
        // }

    }

    updateKeHoach() {
        if (this.idParam != undefined && this.idParam != null) {
            this._serviceApi.execServiceLogin("DC2F3F51-09CC-4237-9284-13EBB85C83C1", [{ "name": "MA_KE_HOACH", "value": this.idParam }]).subscribe((data) => {
                console.log(data.data);
                this._serviceApi.dataKeHoach.next(data.data);
                this.listFile = data.data || [];
                this.listFile = data.data.listFile;
                this.form.get("name").patchValue(data.data.name);
                this.form.get("year").patchValue(data.data.nam);
                this.form.get("maKeHoach").patchValue(this.idParam);
                if (this.listFile != null && this.listFile.length > 0) {
                    for (let i = 0; i < this.listFile.length; i++) {

                        this.listupload.push({
                            fileName: this.listFile[i].fileName,
                            base64: this.listFile[i].base64,
                            duongDan: this.listFile[i].duongDan,
                            size: this.listFile[i].size,
                            sovanban: this.listFile[i].sovanban,
                            mafile: this.listFile[i].mafile
                        });
                    }
                }

            })


        }

    }

    get f(): { [key: string]: AbstractControl } {
        return this.form.controls;
    }



    geListYears() {
        var obj = { "NAME": 0, "ID": 0 };
        var year = (new Date()).getFullYear();
        var yearStart = year - 4;
        var yearEnd = yearStart + 10;
        for (let i = yearStart; i <= yearEnd; i++) {
            obj = { "NAME": i, "ID": i }
            this.listYears.push(obj);
        }
        this.selectedYear = (new Date()).getFullYear();

    }

    // getListStatus() {
    //     this.getStatusSubscription = this._serviceApi.execServiceLogin("E5050E10-799D-4F5F-B4F2-E13AFEA8543B", null).subscribe((data) => {
    //         this.listStatus = data.data || [];
    //     })
    // }
    downloadExcel() {
        let data ="UEsDBBQABgAIAAAAIQAhjEY6cwEAAIwFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEVMluwjAQvVfqP0S+VomBQ1VVBA5dji0S9ANMPCEWiW15Bgp/34lZVFUsQiD1kiix5232TH+4aupkCQGNs7noZh2RgC2cNnaWi6/Je/okEiRltaqdhVysAcVwcH/Xn6w9YMLVFnNREflnKbGooFGYOQ+WV0oXGkX8GWbSq2KuZiB7nc6jLJwlsJRSiyEG/Vco1aKm5G3FvzdKpsaK5GWzr6XKhfK+NoUiFiqXVv8hSV1ZmgK0KxYNQ2foAyiNFQA1deaDYcYwBiI2hkIe5AxQ42WkW1cZV0ZhWBmPD2z9CEO7ctzVtu6TjyMYDclIBfpQDXuXq1p+uzCfOjfPToNcGk2MKGuUsTvdJ/jjZpTx1b2xkNZfBL5QR++fdBDfdZDxeX0UEeaMcaR1DXjr44+g55grFUCPibtodnMBv7FP6eDWHgXnkadHgMtT2LVqW516BoJABvbNeujS7xl59FwdO7SzTYM+wC3jLB38AAAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAACwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVBqDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6pPPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAAgAAAAhAEqppmH6AAAARwMAABoACAF4bC9fcmVscy93b3JrYm9vay54bWwucmVscyCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALySzWrEMAyE74W+g9G9cZL+UMo6eymFvbbbBzCxEodNbGOpP3n7mpTuNrCkl9CjJDTzMcxm+zn04h0jdd4pKLIcBLram861Cl73T1f3IIi1M7r3DhWMSLCtLi82z9hrTk9ku0AiqThSYJnDg5RUWxw0ZT6gS5fGx0FzGmMrg64PukVZ5vmdjL81oJppip1REHfmGsR+DMn5b23fNF2Nj75+G9DxGQvJiQuToI4tsoJp/F4WWQIFeZ6hXJPhw8cDWUQ+cRxXJKdLuQRT/DPMYjK3a8KQ1RHNC8dUPjqlM1svJXOzKgyPfer6sSs0zT/2clb/6gsAAP//AwBQSwMEFAAGAAgAAAAhAPWjrOVQAgAAtgQAAA8AAAB4bC93b3JrYm9vay54bWysVM2O0zAQviPxDpbvbX6adrtR09VuW8QKVFWrpXvpZeo4jaljB9uhrRBPwXPwBBx5Et6ESUKgsJdFcInH9vibme+byeTqWEjynhsrtEpo0Pcp4YrpVKhdQt/cv+iNKbEOVApSK57QE7f0avr82eSgzX6r9Z4ggLIJzZ0rY8+zLOcF2L4uucKbTJsCHG7NzrOl4ZDanHNXSC/0/ZFXgFC0RYjNUzB0lgnG55pVBVeuBTFcgsP0bS5K26EV7ClwBZh9VfaYLkqE2Aop3KkBpaRg8e1OaQNbiWUfg2GHjOYj6EIwo63OXB+hvDbJR/UGvhcEbcnTSSYkX7e0EyjLJRR1FEmJBOsWqXA8TegIt/rAfzswVXlTCYm3QRSFPvWmP6VYGZLyDCrp7lGEDh4dR5EfBLUnFnUtHTcKHJ9p5ZDDH+z/K18N9izXqA654+8qYTg2RU3bdIJfYDFs7QpcTiojEzqPNyuj33LmNov1cnPGLTwW7i/YBVaX6WGdbS6t/WfN00nduWvBD/YXe/WWHB+ESvUhoTgHpzP70Bw/iNTlCQ3HYx/v27OXXOxyhySHg0GjhneG3TQ7xmhWohqR5+AAZ6oeg9taRUpMLNAwt2mj0bnvcld9+/JJkVdC5WSVf/189jA8exg2VXfRGEiGvVAvTYRReBkMag9+dK+ta1aUQST0QxD51xf+ZdTzF4NhLxpfhr1xNAh7s2geLoYXi/niZvjx/3Y+dkPc/TzqLHMw7t4A2+Mv545nN2BxEhomPMwXBeyy9rpX0+8AAAD//wMAUEsDBBQABgAIAAAAIQCypO3BYgQAAF8ZAAANAAAAeGwvc3R5bGVzLnhtbNRZ3Y+bOBB/P+n+B8Q7y0eADVFI1WwWqVKvOt3mpL46YBJfjY3A2U16uv/9xiYE2s3XJiFt92HBw3jm5/F4ZjwZvltlVHvGRUk4C3X7ztI1zGKeEDYP9b+nkdHXtVIgliDKGQ71NS71d6PffxuWYk3x0wJjoYEIVob6Qoh8YJplvMAZKu94jhl8SXmRIQHDYm6WeYFRUspJGTUdy/LNDBGmVxIGWXyKkAwVX5a5EfMsR4LMCCVirWTpWhYPPswZL9CMAtSV7aJYW9l+4dQaFOmVkozEBS95Ku5AqMnTlMT4NdbADEwUN5JA7HmSbM+0nGrho2HKmSi1mC+ZAPNLoBL14AvjLyyS34CqV2yjYflVe0YUKLZujoYxp7zQBFgbFqsoDGW44nhAlMwKItlSlBG6rsiOJKgN2vBlBMwliaYEUuuZSa5al5pzSNeUZLjUPuEX7S+eIfa9ToXslXjSrYqO0W/F95qNKOazUI8iS/1JcrMbZ1lo1xI603FLh/KvYJzX7nNVa19LmHvsnL7ZM7ZecU3R6nSWcPoJpdtg1JNhBwijIcRZgQsWwUDbvE/XOQQdBimhCh6K7wj3vEBr2/FOn1ByShKJYv7QDnWQogSR4dKw7mw3CIK+e+9a967n+I7y49mGn7AEr3AS6r4yltlahwx4CrN6wNJnvEggC9aR2AG1FWk0pDgVcJwLMl/Ip+A5/J9xISBZjIYJQXPOEJUxtJ7RngnZExJlqIsFJLo6aH+PTKrYaDiJX2FRUE5iB8g14pP4q8XtXttmkWCyGFP6JBf3OW0yGCxxlWpsmUWZ+ACmh82SmaV+BZtvXisbVQNpu7a0SnZLrHN/llxtlW4V7ENlA8BdqIBez9ZQntO1zMYyz1ajsfKXZvyekjnLcMUyGkL6rYbaghfkK0yVeTuG77jQZb0lSNymvBQon+KVUiCtsUr32/GWiP9ZloKk658d8mUGharrF3OBrhFfZs/eL2fPWyK+0pHqGvJlLuDucQFIB4ei6mVR9Fjg9DoEJTP4jij5IyHtzTbHQAW3P7+dQwIF+yoA/61ucUAWdEsuSyVdyq4ql7ecsWPbIqu73SXdSaXXLSuZPQdUO7PyggzcVLBHakV5cfopKsf77qNyxx6zz+FOrtYPnC/oqnV3eO2LkV//9F6+4B8SUc5Xqi6ZcK1s3V2/ublu76CabACF+ifZu6atkmW2JBR6DzturSAzWTX3YEt2OYTsQ6sb8lYLeEGCU7SkYrr9GOrN+x84IcsMgsuG60/yzIUSEerN+0fZirBVHw3ujB9L6B3AU1sWJNT/fRzfB5PHyDH61rhvuD3sGYE3nhie+zCeTKLAcqyH/1oN8Qva4ap5D4nVdgclhaZ5sVnsBvxTQwv11qCCr/pAALuNPXB8671nW0bUs2zD9VHf6Ps9z4g825n47vjRi7wWdu/MBrxl2nbdgF/Z3kBAB5sSVu9VvUNtKmwSDA8swqx3wmx+GRn9DwAA//8DAFBLAwQUAAYACAAAACEAE8QsE8IAAABCAQAAIwAAAHhsL3dvcmtzaGVldHMvX3JlbHMvc2hlZXQyLnhtbC5yZWxzhI/BasMwEETvhfyD2HskO4dQiiVfSiHXJv0ARV7bovZKaLcl+fvo2IRCjsNj3jBdf1kX9YuFYyILrW5AIYU0RJosfJ0+tq+gWDwNfkmEFq7I0LvNS/eJi5da4jlmVtVCbGEWyW/GcJhx9axTRqpkTGX1UmOZTPbh209odk2zN+WvA9ydUx0GC+UwtKBO11yXn7vTOMaA7yn8rEjyz4TJJZJgOaJIPchV7cuEYkHrR/aYd/ocCYzrzN1zdwMAAP//AwBQSwMEFAAGAAgAAAAhADttMkvBAAAAQgEAACMAAAB4bC93b3Jrc2hlZXRzL19yZWxzL3NoZWV0MS54bWwucmVsc4SPwYrCMBRF9wP+Q3h7k9aFDENTNyK4VecDYvraBtuXkPcU/XuzHGXA5eVwz+U2m/s8qRtmDpEs1LoCheRjF2iw8HvaLb9BsTjq3BQJLTyQYdMuvpoDTk5KiceQWBULsYVRJP0Yw37E2bGOCamQPubZSYl5MMn5ixvQrKpqbfJfB7QvTrXvLOR9V4M6PVJZ/uyOfR88bqO/zkjyz4RJOZBgPqJIOchF7fKAYkHrd/aea30OBKZtzMvz9gkAAP//AwBQSwMEFAAGAAgAAAAhAA7l8pKJAgAAtQUAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0Mi54bWycVE1P4zAUvK+0/8HynXxRCkRNEWyFlsNKK9iPs+s4jUUSe223pfz6HdttqIAD4lLH8Xszb6YTz66e+o5shLFSDRXNk4wSMXBVy2FV0d+/bk8uKLGODTXr1CAquhOWXs2/fpltlXm0rRCOAGGwFW2d02WaWt6KntlEaTHgpFGmZw5bs0qtNoLVoanv0iLLpmnP5EAjQmk+gqGaRnKxUHzdi8FFECM65jC/baW2B7SefwSuZ+ZxrU+46jUglrKTbhdAKel5ebcalGHLDrqf8gnjB+yweQPfS26UVY1LAJfGQd9qvkwvUyDNZ7WEAm87MaKp6HVe3kxoOp8Ff/5IsbVHz8TbvVTq0R/c1RXNgGBFJ7gXThiWjfgmuq6iiwL/2L+AiUcApiPi8fMB/Tb8QT8NqUXD1p27V9vvQq5ahzScQbDXXda7hbAchoM4Kc48KlcdIPBLeumTA8PYU1i3snZtRS+TfJJNUYz87LyFxXTfFzswZujAuu8osrFlKay7lX4GSvjaOtX/jah5UBTJg64Fc2w+M2pLkB9UW818GvPS24D1/AAQhYaaIO4iOX9f3yms5R7t2sNh7gklmMTi9WY+yWfpBj7yfc3NvgZsLzXFWJNisHE6P9HRdB+dIgqBkZ7/Nf3+8PSY/n12lHyG3bfBg8j+IiwYdBMPc9wRo/jz99nh4WfYfdvIfvrK+v3hsfbiNX0MfwyJZivxg5mVHCzpRBPCjHiYmPYswbNT2kfcJ2OpHGJ32LW4uQQykSWga5Ryhw0+BY/7INxaE820MA/y2af9bEqJMhIfTbicKqqVcYZJR0mL988KB91CS5RmwMQd7CQ/fmNKiQ/d3NUx8+OFO/8PAAD//wMAUEsDBBQABgAIAAAAIQB1PplpkwYAAIwaAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbOxZW4vbRhR+L/Q/CL07vkmyvcQbbNlO2uwmIeuk5HFsj63JjjRGM96NCYGSPPWlUEhLXwp960MpDTTQ0Jf+mIWENv0RPTOSrZn1OJvLprQla1ik0XfOfHPO0TcXXbx0L6bOEU45YUnbrV6ouA5OxmxCklnbvTUclJquwwVKJoiyBLfdJebupd2PP7qIdkSEY+yAfcJ3UNuNhJjvlMt8DM2IX2BznMCzKUtjJOA2nZUnKToGvzEt1yqVoBwjkrhOgmJwe306JWPsDKVLd3flvE/hNhFcNoxpeiBdY8NCYSeHVYngSx7S1DlCtO1CPxN2PMT3hOtQxAU8aLsV9eeWdy+W0U5uRMUWW81uoP5yu9xgclhTfaaz0bpTz/O9oLP2rwBUbOL6jX7QD9b+FACNxzDSjIvu0++2uj0/x2qg7NLiu9fo1asGXvNf3+Dc8eXPwCtQ5t/bwA8GIUTRwCtQhvctMWnUQs/AK1CGDzbwjUqn5zUMvAJFlCSHG+iKH9TD1WjXkCmjV6zwlu8NGrXceYGCalhXl+xiyhKxrdZidJelAwBIIEWCJI5YzvEUjaGKQ0TJKCXOHplFUHhzlDAOzZVaZVCpw3/589SVigjawUizlryACd9oknwcPk7JXLTdT8Grq0GeP3t28vDpycNfTx49Onn4c963cmXYXUHJTLd7+cNXf333ufPnL9+/fPx11vVpPNfxL3764sVvv7/KPYy4CMXzb568ePrk+bdf/vHjY4v3TopGOnxIYsyda/jYucliGKCFPx6lb2YxjBAxLFAEvi2u+yIygNeWiNpwXWyG8HYKKmMDXl7cNbgeROlCEEvPV6PYAO4zRrsstQbgquxLi/BwkczsnacLHXcToSNb3yFKjAT3F3OQV2JzGUbYoHmDokSgGU6wcOQzdoixZXR3CDHiuk/GKeNsKpw7xOkiYg3JkIyMQiqMrpAY8rK0EYRUG7HZv+10GbWNuoePTCS8FohayA8xNcJ4GS0Eim0uhyimesD3kIhsJA+W6VjH9bmATM8wZU5/gjm32VxPYbxa0q+CwtjTvk+XsYlMBTm0+dxDjOnIHjsMIxTPrZxJEunYT/ghlChybjBhg+8z8w2R95AHlGxN922CjXSfLQS3QFx1SkWByCeL1JLLy5iZ7+OSThFWKgPab0h6TJIz9f2Usvv/jLLbNfocNN3u+F3UvJMS6zt15ZSGb8P9B5W7hxbJDQwvy+bM9UG4Pwi3+78X7m3v8vnLdaHQIN7FWl2t3OOtC/cpofRALCne42rtzmFemgygUW0q1M5yvZGbR3CZbxMM3CxFysZJmfiMiOggQnNY4FfVNnTGc9cz7swZh3W/alYbYnzKt9o9LOJ9Nsn2q9Wq3Jtm4sGRKNor/rod9hoiQweNYg+2dq92tTO1V14RkLZvQkLrzCRRt5BorBohC68ioUZ2LixaFhZN6X6VqlUW16EAauuswMLJgeVW2/W97BwAtlSI4onMU3YksMquTM65ZnpbMKleAbCKWFVAkemW5Lp1eHJ0Wam9RqYNElq5mSS0MozQBOfVqR+cnGeuW0VKDXoyFKu3oaDRaL6PXEsROaUNNNGVgibOcdsN6j6cjY3RvO1OYd8Pl/EcaofLBS+iMzg8G4s0e+HfRlnmKRc9xKMs4Ep0MjWIicCpQ0ncduXw19VAE6Uhilu1BoLwryXXAln5t5GDpJtJxtMpHgs97VqLjHR2CwqfaYX1qTJ/e7C0ZAtI90E0OXZGdJHeRFBifqMqAzghHI5/qlk0JwTOM9dCVtTfqYkpl139QFHVUNaO6DxC+Yyii3kGVyK6pqPu1jHQ7vIxQ0A3QziayQn2nWfds6dqGTlNNIs501AVOWvaxfT9TfIaq2ISNVhl0q22DbzQutZK66BQrbPEGbPua0wIGrWiM4OaZLwpw1Kz81aT2jkuCLRIBFvitp4jrJF425kf7E5XrZwgVutKVfjqw4f+bYKN7oJ49OAUeEEFV6mELw8pgkVfdo6cyQa8IvdEvkaEK2eRkrZ7v+J3vLDmh6VK0++XvLpXKTX9Tr3U8f16te9XK71u7QFMLCKKq3720WUAB1F0mX96Ue0bn1/i1VnbhTGLy0x9Xikr4urzS7W2/fOLQ0B07ge1Qave6galVr0zKHm9brPUCoNuqReEjd6gF/rN1uCB6xwpsNeph17Qb5aCahiWvKAi6TdbpYZXq3W8RqfZ9zoP8mUMjDyTjzwWEF7Fa/dvAAAA//8DAFBLAwQUAAYACAAAACEA4304CxAGAAAGGQAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbKxZTZOiSBC9b8T+B4L7iCBqN6FOtAo4h43Y2NmPM42lEiOWC3T3zL/frA+gKpOdYTv20rTPl1m8yqysrHL18Wt5dV5ZVRf8tnb9ydR12C3nx+J2Xrt//J58eHCduslux+zKb2ztfmO1+3Hz80+rN159qS+MNQ54uNVr99I098jz6vzCyqye8Du7wTcnXpVZAx+rs1ffK5YdpVF59YLpdOGVWXFzlYeoGuODn05FzvY8fynZrVFOKnbNGnj/+lLc69ZbmY9xV2bVl5f7h5yXd3DxXFyL5pt06jplHn0633iVPV9B91c/zPLWt/xA3JdFXvGan5oJuPPUi1LNj96jB542q2MBCsS0OxU7rd0nPzrMlq63WckJ+rNgb7Xxv9Nkz5/ZleUNO0KcXEfM/zPnXwTxE0BTcFlLgnCZ5U3xynbsegXPIYTwbzVIGD0txBheN4j5fztgIoP2a+Uc2Sl7uTa/8bcDK86XBkaewySIuYiO3/asziEIMPYkmAuvOb+CC/jrlIXIJpjE7Kt62+LYXOA/YD7M/fkC+E7+Uje8/Et/o+2VZaAt4fmmvg+X4yxn2hKe2tJfTObL6cz/wZAwSfJl4cVaw2ASBvPlw48sF9oSntoy8MdZLrUlPDvL784LLEb5kvDUBrPpxA+n/zKfngqIjPU+a7LNquJvDqwziEx9z8Sq9SPwJQILjpZdULpoDwZ7BqmWCzdPws/aDaBogIca4NdNMFt5r5BUueZsNceXARZWO4LsCRITJCFISpCDiXigtRMMiYQFB8Hkv+rdCjdY74Otd6c5vd49QWKCJARJCXIwEUsdJPv71cG6aMMp/Kzdxy5SWwX40z52BNlrpNcbEyQhSIqHOhiApU0UL5Sqi0DUG10/vp+qhjjhCPL90cjVKUrVAUrwiMI7wPERZz/AmaGx4qGx5vZYyRBnYXPSofexKYchN2HHsWYbptWc7eFK36aLIMsZFaVfrOwtQXYE2RMkJkhCkJQgBxOxNEAdHq9BkG0NBNkRZE+QmCAJQVKCHEzE0gA7gqlBvCJEUe2YaneWRVztyLJwfz9Uwh9YQAXpCvXMR9mvObAQe06Asl9zunqwx0CMgQQDqQJmnY+DAgLZl5hFW7SeaOn78xFihR2IhcntdyWkVVMgh3qtSKqihL1UDMQYSDCQKkD1RmKBHAyGFW+oSu+SKuyQVFREtppiSkU1ZKcosjGU63iPgRgDCQZSBTz0UVWA7GgtqbCb/L+5LR3i5CZdiBgVSGZ24527ddSHnCAxQRKCpBqRCS3n82By7MkY6MRG5bivWh0rydE2tG05ZugDtA/tWpIhWrvukJhwEoKkGjFFG35s0QPd2DjRqgOyRPu4jIkiJyJtqvaJak0yVGMkbh11nIQgqUZM1YYfW/VAlzZOte6ezHrmo8K8FYmNVc/6TV6m4a4lGaq1mRFrjCTEKtWIqdqwslUP9G/jVOuuxVKNBG3FpohVByghdppklDeCxARJCJJqRFY0vazV8OpEbe5cIvneVc+lId67SKx162NlOCp4O+3JVK3MeiQmnIQgqUZM1YYfO9ao8xrdnYgFjbexGd7HWpK1Z+OdTJNM1cq3qRojCbFKNWKqNqxs1ahXG696qClb4tPzUFdGNi7SlvmkLyNIQpBUI+a6NvzYqt/bnPkD3ZlPYj3Qn/kk1opkxhojsR6t5yQESTVixtrwY6t+b58mjp04w30S64FWzSexJs2a9m1mOGnXCCfViKnasLIvT1DHNjrDxcUQOXbgLqUlmZ1ZiPfrltTvXASJCZIQJNWIkeEmx75UgdQ3lKqz1w9vG7q7VXXfVrLqLK9hayfnL+KuFFrBzaqD1d3vPozgSAmmCN+FERw+KS7uiuV9C+I/tde7CN+G0XbITxJGcEyl/tMwgsMqxQ9hBEdWisdhBAdgim+DCC6txJT087BZ3bMz+yWrzsWtdq7sJO+PYa4rdcEM15BwKON3cassLiSfeQO3xO2nC/yAwOAgNZ1Aupw4b9oPMIjw+5k1L3eHVwXcS8vfBNbunVdNlRUNjBAVcFFefTrKufO6XzA2/wAAAP//AwBQSwMEFAAGAAgAAAAhACesrq0dAwAAYwcAABQAAAB4bC9zaGFyZWRTdHJpbmdzLnhtbIxVz0sbQRS+F/o/PPZkwWaTTSsiSYTGtinStNDYqyyT7e5iMhMzs0GP1UOhpaB46A+QGkRE26JCT1mkh13yf8x/0jebmMQdYz3t7jczb9773vu+LSxuNBvQcdrcZ7Ro5DJZAxxKWN2nbtFYqT17OG8AFzat2w1GnaKx6XBjsXT/XoFzAXiW8qLhCdFaME1OPKdp8wxrORRX3rF20xb42XZN3mo7dp17jiOaDdPKZufMpu1TAwgLqCgaj/IGBNRfD5zyCCgVuF8qiNKbWq1gilLBVJ8DqCrDbz7UA+qCx2SvKyDeRYi66Y25TE476/ky/NCEjgyPYLlSrgKRvaMWPH1bTW+9AcplrLsGJP0ucBn+SO+Pd/pdqq7/lF5ZQox448zS65ZezeQR4gWbMtym4Po2AxL9QXqo62G1eiCtCiuTvy2deDc6YCCQazYLGPKwBSLqkoRAPfqjNJTXMy9PYz2vUzzYO43QqhvIcI/Cmk89aHnRb5jBzpljnh/cVplqkaroLADRxrMCg2mETdIsvIRZ4dMp1T9OX/fkhQy3VuCl7J2uQLwTb1Wfw3K0j68y/FitQKV/JsPvCFZeyd5BLcG/qj04nelYNUx131ctplCX4QVWLXt/KQjELwgkw01hRsjwJ2JRl7omjbebSiCDbSNIY2VMGBCMdqz4+JW+v5ys0KGIrp5KTJourtqCWRBtEXNaACtraVM3oe14N97GGV6LLm9o4AUIhrVgqW0l6CCxgD3qamX93wG0AU4ByucWeMsm6H9oZNxpdxyjdG0m/Og0QNYC2Tuhs5gKg0b/HDtF3VlFZu9IDIBD6q5uZLPZpVW00JSrWZm5O108CjB6qVwzQWhgNhTWAxyRNUU+igL7QxJjSdT7BVuLGtYDEY9BR9FJlHMkYYgMTwKMw2ylks8YJTpQKkPTTZhHv5m0GnTT8NhWbgomDvKV1eEsOgy/Mfb7AOahNhRR/xxy1lRGtOFIFcrVMA8VkGZT86Cy5w/cQRU5SDmxsHVs2iGFRnSZ+pncrD/9ZzSc82VlP6/RfsaZmPiTLP0DAAD//wMAUEsDBBQABgAIAAAAIQBvXxoDYgEAAGoCAAARAAgBZG9jUHJvcHMvY29yZS54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEkk1OwzAQhfdI3CHyPnXi0lJZTSp+1BVFSIQfsbPsaRsRO5HtknaNOAqXgC0X6U1wkjakAoml57359N7I48laZt4LaJPmKkJhL0AeKJ6LVC0idJdM/RHyjGVKsCxXEKENGDSJj4/GvKA813Cj8wK0TcF4jqQM5UWEltYWFGPDlyCZ6TmHcuI815JZ99QLXDD+zBaASRAMsQTLBLMMV0C/aIlohxS8RRYrndUAwTFkIEFZg8NeiH+8FrQ0fy7USscpU7spXKdd3C5b8EZs3WuTtsayLHtlv47h8of4cXZ1W1f1U1XdigOKx4JTroHZXMdnQqZqjDuT6noZM3bmDj1PQZxv4uvFarP9fFPe/der8pLV9uPd7fz2OXDdo6GD8Fwy2vTYKw/9i8tkimISkL4fnPjBMAkIHYSUkKcqxsF+lbQZyF2Yf4kjn5AkDCgZ0P5ph7gHxHXuw98RfwMAAP//AwBQSwMEFAAGAAgAAAAhAKkIIODvAAAA8AUAACcAAAB4bC9wcmludGVyU2V0dGluZ3MvcHJpbnRlclNldHRpbmdzMi5iaW5yZ8hnSGFIZahgUGBwZzBlMABCUgAjCxP7HQYRVn5VRgZGBgbGH8yCLClg1mkgycgAIhkYQhmCGVwZgkgymbBiJqASZiAG2QAhUPUsAQr6uoT4gdSxAvFpkLQkA8MTHoi6HdwMDAXiEPYdoIIIkEIk8O8/bjeYA824BcQC6qh4ARcDwyE2BoYdQKzDwsDgAHTcJaAxEmCjBNRBEKIDt9mjMqMhMBoCIyMEMlgYgaUEA8M5YAGBXPwwgXlC4NL4PxCAyzigOlCZBcIg8P7s6gkwcRBf4gMjAweQlkMLOpCa4uLi9JSKAhYAAAAA//8DAFBLAwQUAAYACAAAACEAoR90vrUBAADVEgAAJwAAAHhsL3ByaW50ZXJTZXR0aW5ncy9wcmludGVyU2V0dGluZ3MxLmJpbuxY3UoCQRT+Vg1FWKQHCHyBojS8CILMf/FncbcyWAjRAiESSoPAh+gNeh+foSfoqrvoorZvRy3bVkrNH9g9sDNzZs7Mzvnm7JmPzUJBGAXUcINzXCPPss0ehe0W6yJ2sY0INgetKPuuqDVYmiL5NuRHvK6HXuCRIOEp2Ao0WPtR9XCUJat5i2T/Ag96veFIgt506FNTeDn5hrKcd4lbgU4TdeI1mQRtzE2ErDLGlfljuPQ3+GEYIqIYNWD89LXR1iqBcKDkC2E1pYUzRzlVi1e0fPlwf0e2O2YHnJ3r4qIRGI2/VCnpyOiz5spJde/noQUGmfhn9n1AYKqj7a/0vOYX2cy6xDC3jVs67bW/B36b9/etJrAHHSfIoYQkymyp1FWc8tGQ4m0f5a1v9igcLZMh6LSr0P6YoxVhXUWM7ECnpY4s7cx1YoItxHGG/mgCaWSwRa3INVxxEVgEAmnyszp5bIuM746MNUnedsG+Djlcm0z3v0SGvPQD9Vl2YBjvxptgUqsRa85ltO637iLgIrCiCES+7StE7f4rU8XFn4Iab4vppIvuTG7POt/hUfcBAAD//wMAUEsDBBQABgAIAAAAIQB8UBcQowEAADUDAAAQAAgBZG9jUHJvcHMvYXBwLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJyTS27bMBCG9wV6B4H7mIobBIVBMSicBgH6MmAnWbPUyCJCkQQ5Fuxeo+foCbrsSXKTjCREkZNFgO7m8ePnxxlSXOwbm7UQk/GuYKeznGXgtC+N2xbsZnN18pFlCZUrlfUOCnaAxC7k+3diFX2AiAZSRhYuFaxGDAvOk66hUWlGbUedysdGIaVxy31VGQ2XXu8acMjneX7OYY/gSihPwmjIBsdFi/9rWnrd8aXbzSEQsBSfQrBGK6Rbym9GR598hdnnvQYr+LQpiG4NehcNHmQu+DQVa60sLMlYVsomEPy5IK5BdUNbKROTFC0uWtDoY5bMLxrbnGU/VYIOp2CtikY5JKxONiR9bEPCKO98vE81ACbBSTAU+3CqncbmTM57AQXHws5gAKHGMeLGoIX0o1qpiG8R9wwD74BzqVBN6UbO79vdw9/fLvtiXJ2t6n9/Xt2hHwvRvDh/6Zug3IEaY/TVuPt0EzaeToOnkR8XxbpWEUra0riSsSCuadrRdibLWrktlE+a143ugdwOv0Cens/yDzntflIT/Pm9y0cAAAD//wMAUEsBAi0AFAAGAAgAAAAhACGMRjpzAQAAjAUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAtVUwI/QAAABMAgAACwAAAAAAAAAAAAAAAACsAwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEASqmmYfoAAABHAwAAGgAAAAAAAAAAAAAAAADRBgAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAYACAAAACEA9aOs5VACAAC2BAAADwAAAAAAAAAAAAAAAAALCQAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhALKk7cFiBAAAXxkAAA0AAAAAAAAAAAAAAAAAiAsAAHhsL3N0eWxlcy54bWxQSwECLQAUAAYACAAAACEAE8QsE8IAAABCAQAAIwAAAAAAAAAAAAAAAAAVEAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDIueG1sLnJlbHNQSwECLQAUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAAAAAAAAAAAAAAAYEQAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECLQAUAAYACAAAACEADuXykokCAAC1BQAAGAAAAAAAAAAAAAAAAAAaEgAAeGwvd29ya3NoZWV0cy9zaGVldDIueG1sUEsBAi0AFAAGAAgAAAAhAHU+mWmTBgAAjBoAABMAAAAAAAAAAAAAAAAA2RQAAHhsL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEA4304CxAGAAAGGQAAGAAAAAAAAAAAAAAAAACdGwAAeGwvd29ya3NoZWV0cy9zaGVldDEueG1sUEsBAi0AFAAGAAgAAAAhACesrq0dAwAAYwcAABQAAAAAAAAAAAAAAAAA4yEAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAi0AFAAGAAgAAAAhAG9fGgNiAQAAagIAABEAAAAAAAAAAAAAAAAAMiUAAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAKkIIODvAAAA8AUAACcAAAAAAAAAAAAAAAAAyycAAHhsL3ByaW50ZXJTZXR0aW5ncy9wcmludGVyU2V0dGluZ3MyLmJpblBLAQItABQABgAIAAAAIQChH3S+tQEAANUSAAAnAAAAAAAAAAAAAAAAAP8oAAB4bC9wcmludGVyU2V0dGluZ3MvcHJpbnRlclNldHRpbmdzMS5iaW5QSwECLQAUAAYACAAAACEAfFAXEKMBAAA1AwAAEAAAAAAAAAAAAAAAAAD5KgAAZG9jUHJvcHMvYXBwLnhtbFBLBQYAAAAADwAPABIEAADSLQAAAAA=";
        this.downloadTempExcel(data, "MAU_DANG_KY_DINH_HUONG.xlsx");
        //this._serviceApi.execServiceLogin("B186CEDA-876B-4511-96D1-E199926A6913", [{ "name": "ORGID", "value": "115" }]).subscribe((data) => {
         //   this.downloadTempExcel(data.data, "MAU_DANG_KY_DINH_HUONG.xlsx");
      //  })
    }

    importFile(event) {
        this.showTable = false
        const file = event.target.files[0];
        const formTem = this.form.value;
        this.form = this._formBuilder.group({
            name: [formTem.name, [Validators.required]],
            year: [formTem.year, [Validators.required]],
            maKeHoach: this.idParam,
            listChiTietImport: [],
        }
        )

        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            let fileBase64 = reader.result.toString().split(',')[1];
            this._serviceApi.execServiceLogin("1E707636-93B5-43EA-97BC-2F850C14D1E3", [{ "name": "ORGID", "value": "115" }, { "name": "FILE_UPLOAD", "value": fileBase64 }]).subscribe((data) => {
              
                let arr = data.data || [];
                let capTao = "DONVI";
                if (this.listDonvi != null && this.listDonvi.length > 0) {
                    capTao = 'TCT';
                }
                let kehoach = {
                    capTao: capTao,
                    listKeHoach: arr
                };
                this._serviceApi.dataKeHoach.next(kehoach);
                this.listChiTietImport = data.data || [];
                this.showTable = true
            })
        };
    }




    downloadTempExcel(userInp, fileName) {
        var mediaType = "data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,";
        // var userInp = document.getElementById('base64input');
        // var userInp = "UEsDBBQABgAIAAAAIQBBN4LPbgEAAAQFAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsVMluwjAQvVfqP0S+Vomhh6qqCBy6HFsk6AeYeJJYJLblGSj8fSdmUVWxCMElUWzPWybzPBit2iZZQkDjbC76WU8kYAunja1y8T39SJ9FgqSsVo2zkIs1oBgN7+8G07UHTLjaYi5qIv8iJRY1tAoz58HyTulCq4g/QyW9KuaqAvnY6z3JwlkCSyl1GGI4eINSLRpK3le8vFEyM1Ykr5tzHVUulPeNKRSxULm0+h9J6srSFKBdsWgZOkMfQGmsAahtMh8MM4YJELExFPIgZ4AGLyPdusq4MgrD2nh8YOtHGLqd4662dV/8O4LRkIxVoE/Vsne5auSPC/OZc/PsNMilrYktylpl7E73Cf54GGV89W8spPMXgc/oIJ4xkPF5vYQIc4YQad0A3rrtEfQcc60C6Anx9FY3F/AX+5QOjtQ4OI+c2gCXd2EXka469QwEgQzsQ3Jo2PaMHPmr2w7dnaJBH+CW8Q4b/gIAAP//AwBQSwMEFAAGAAgAAAAhALVVMCP0AAAATAIAAAsACAJfcmVscy8ucmVscyCiBAIooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACskk1PwzAMhu9I/IfI99XdkBBCS3dBSLshVH6ASdwPtY2jJBvdvyccEFQagwNHf71+/Mrb3TyN6sgh9uI0rIsSFDsjtnethpf6cXUHKiZylkZxrOHEEXbV9dX2mUdKeSh2vY8qq7iooUvJ3yNG0/FEsRDPLlcaCROlHIYWPZmBWsZNWd5i+K4B1UJT7a2GsLc3oOqTz5t/15am6Q0/iDlM7NKZFchzYmfZrnzIbCH1+RpVU2g5abBinnI6InlfZGzA80SbvxP9fC1OnMhSIjQS+DLPR8cloPV/WrQ08cudecQ3CcOryPDJgosfqN4BAAD//wMAUEsDBBQABgAIAAAAIQBFujwYXQMAAFoIAAAPAAAAeGwvd29ya2Jvb2sueG1srFXvb5s8EP7+SvsfEN8pxgECqHQqBPRWaqeqzdovlSYXTLEKOLNNk6ra/74zhPTXNGXdosTGvuPxc77nLoefN21jPFAhGe9i0zlApkG7gpesu4vNr8vcCkxDKtKVpOEdjc1HKs3PR5/+O1xzcX/L+b0BAJ2MzVqpVWTbsqhpS+QBX9EOLBUXLVGwFHe2XAlKSllTqtrGxgj5dktYZ44IkdgHg1cVK+iCF31LOzWCCNoQBfRlzVZyQmuLfeBaIu77lVXwdgUQt6xh6nEANY22iE7uOi7IbQNhbxzP2Aj4+vBzEAx4OglM745qWSG45JU6AGh7JP0ufgfZjvPqCjbv72A/JNcW9IHpHO5YCf+DrPwdlv8M5qC/RnNAWoNWIri8D6J5O27YPDqsWEOvRukaZLX6QlqdqcY0GiJVVjJFy9icw5Kv6asN0a+SnjVgxTMfB6Z9tJPzuTBKWpG+UUsQ8gQPleH7Ifa0JwjjuFFUdETRlHcKdLiN6281N2CnNQeFGxf0e88EhcICfUGsMJIiIrfynKja6EUTm2l081VC+DeSqlreTEUhb14ok7wvgz/QJil0wDZEPLIan99GD+RENOnvXAkDnk8Wp5CDS/IAGYG8l9uCPYErD749hYEfJug4tAK88CwX48AKk3loeW6a+OnxDOez+Q+IQvhRwUmv6m2WNWZsulqXb01nZDNZHBT1rHw+/wltP5ae3wyT7YeOVPezK0bX8lkPemlsrllX8nVsWo5W8ePr5XowXrNS1aCT0MXgMu79T9ldDYwdNGyC7jWz2HxCWT6fp1lqBUE+s9xFkFthnodWFqYo8HGKMcIDI/sFpaFzArVhNrpB7Ze6mzrQovWsbxeeRaTPECelM2Rveq0gTQHq1tPgGDoIh9qDbtSpVMMMwmJAz3HR8RyFroWyGeQnCLEVuDNspe4CZ948W2SJp/OjO3/0L/rfoO9o+kvRLGsi1FKQ4h7+iC5olRAJShoDAr4vySZekKAZUHRzJ7dcJ0RWkviu5S3ymTd3Fmnm5c9kdfjVB7tPYA9vU6J6qExdlMM60mO+3d1tVuPGNk+vii66WOh73779O8dLiL6hezrnV3s6pl/Olmd7+p5my2/X+SCkX0ZrD9nQ46Ahe8rh0U8AAAD//wMAUEsDBBQABgAIAAAAIQCBPpSX8wAAALoCAAAaAAgBeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsUk1LxDAQvQv+hzB3m3YVEdl0LyLsVesPCMm0KdsmITN+9N8bKrpdWNZLLwNvhnnvzcd29zUO4gMT9cErqIoSBHoTbO87BW/N880DCGLtrR6CRwUTEuzq66vtCw6acxO5PpLILJ4UOOb4KCUZh6OmIkT0udKGNGrOMHUyanPQHcpNWd7LtOSA+oRT7K2CtLe3IJopZuX/uUPb9gafgnkf0fMZCUk8DXkA0ejUISv4wUX2CPK8/GZNec5rwaP6DOUcq0seqjU9fIZ0IIfIRx9/KZJz5aKZu1Xv4XRC+8opv9vyLMv072bkycfV3wAAAP//AwBQSwMEFAAGAAgAAAAhAAdhSeKLAgAARAYAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWyclV9v2jAUxd8n7TtYfof8IUCJklSFCK0Pk6Z127txbsBqEnu2gXbTvvuuk5GmsE2oEiA7Pv7d4/jYJLdPdUUOoI2QTUqDsU8JNFwWotmm9OuX9eiGEmNZU7BKNpDSZzD0Nnv/LjlK/Wh2AJYgoTEp3VmrYs8zfAc1M2OpoMGRUuqaWezqrWeUBla0k+rKC31/5tVMNLQjxPoahixLwSGXfF9DYzuIhopZ9G92QpkTrebX4GqmH/dqxGWtELERlbDPLZSSmsf320Zqtqlw3U9BxDh50vgJ8Ts5lWmfX1SqBdfSyNKOkex1ni+Xv/AWHuM96XL9V2GCyNNwEG4DX1Dh2ywF054VvsAmb4TNeph7XTreiyKlP+d3q/wmDxajSeQvR1EeYcZmK3/kr6eL+XI5W4fL8BfNkkLgDrtVEQ1lSu+COJ9QL0va/HwTcDSDNrFs8wAVcAtYI6DExXMj5aMT3uMjH4mmFTgi41YcYAVVldL1FBP+va2BTSzg9RWG7VO1dRvoT5oUULJ9ZT/L4wcQ253FstEYWW0i4uI5B8Mxolh6PGm5LTZnlmWJlkeC240+jWLu8ARx9K+ZWcKd9s6J2ymINLiaQzZPvANa5H8Uy0uF/1qxulQErxX5pSLsFR7a7r1jPq737sQpxd/e++TM+3AsOnM9HJue+R2Ozf7uFMN3vVMn/r9TVPSruDlzOhxbnDkdjgUvG9O91C5zXTgU28JHpreiMaSCsk3QnBLdhcwfY9tK5XI1x7htpLWyPvV2eMECpgUzR0kppT11MNeO+wB2r4hiCvSD+IH32oISqQXmtL1BU6qktpoJS92fghWcVbkS7vgQHbvjq++LoD0k/f2f/QYAAP//AwBQSwMEFAAGAAgAAAAhAMEXEL5OBwAAxiAAABMAAAB4bC90aGVtZS90aGVtZTEueG1s7FnNixs3FL8X+j8Mc3f8NeOPJd7gz2yT3SRknZQctbbsUVYzMpK8GxMCJTn1UiikpZdCbz2U0kADDb30jwkktOkf0SfN2COt5SSbbEpadg2LR/69p6f3nn5683Tx0r2YekeYC8KSll++UPI9nIzYmCTTln9rOCg0fE9IlIwRZQlu+Qss/Evbn35yEW3JCMfYA/lEbKGWH0k52yoWxQiGkbjAZjiB3yaMx0jCI58Wxxwdg96YFiulUq0YI5L4XoJiUHt9MiEj7A2VSn97qbxP4TGRQg2MKN9XqrElobHjw7JCiIXoUu4dIdryYZ4xOx7ie9L3KBISfmj5Jf3nF7cvFtFWJkTlBllDbqD/MrlMYHxY0XPy6cFq0iAIg1p7pV8DqFzH9ev9Wr+20qcBaDSClaa22DrrlW6QYQ1Q+tWhu1fvVcsW3tBfXbO5HaqPhdegVH+whh8MuuBFC69BKT5cw4edZqdn69egFF9bw9dL7V5Qt/RrUERJcriGLoW1ane52hVkwuiOE94Mg0G9kinPUZANq+xSU0xYIjflWozuMj4AgAJSJEniycUMT9AIsriLKDngxNsl0wgSb4YSJmC4VCkNSlX4rz6B/qYjirYwMqSVXWCJWBtS9nhixMlMtvwroNU3IC+ePXv+8Onzh789f/To+cNfsrm1KktuByVTU+7Vj1///f0X3l+//vDq8Tfp1CfxwsS//PnLl7//8Tr1sOLcFS++ffLy6ZMX333150+PHdrbHB2Y8CGJsfCu4WPvJothgQ778QE/ncQwQsSSQBHodqjuy8gCXlsg6sJ1sO3C2xxYxgW8PL9r2bof8bkkjpmvRrEF3GOMdhh3OuCqmsvw8HCeTN2T87mJu4nQkWvuLkqsAPfnM6BX4lLZjbBl5g2KEommOMHSU7+xQ4wdq7tDiOXXPTLiTLCJ9O4Qr4OI0yVDcmAlUi60Q2KIy8JlIITa8s3eba/DqGvVPXxkI2FbIOowfoip5cbLaC5R7FI5RDE1Hb6LZOQycn/BRyauLyREeoop8/pjLIRL5jqH9RpBvwoM4w77Hl3ENpJLcujSuYsYM5E9dtiNUDxz2kySyMR+Jg4hRZF3g0kXfI/ZO0Q9QxxQsjHctwm2wv1mIrgF5GqalCeI+mXOHbG8jJm9Hxd0grCLZdo8tti1zYkzOzrzqZXauxhTdIzGGHu3PnNY0GEzy+e50VciYJUd7EqsK8jOVfWcYAFlkqpr1ilylwgrZffxlG2wZ29xgngWKIkR36T5GkTdSl045ZxUep2ODk3gNQLlH+SL0ynXBegwkru/SeuNCFlnl3oW7nxdcCt+b7PHYF/ePe2+BBl8ahkg9rf2zRBRa4I8YYYICgwX3YKIFf5cRJ2rWmzulJvYmzYPAxRGVr0Tk+SNxc+Jsif8d8oedwFzBgWPW/H7lDqbKGXnRIGzCfcfLGt6aJ7cwHCSrHPWeVVzXtX4//uqZtNePq9lzmuZ81rG9fb1QWqZvHyByibv8uieT7yx5TMhlO7LBcW7Qnd9BLzRjAcwqNtRuie5agHOIviaNZgs3JQjLeNxJj8nMtqP0AxaQ2XdwJyKTPVUeDMmoGOkh3UrFZ/QrftO83iPjdNOZ7msupqpCwWS+XgpXI1Dl0qm6Fo9796t1Ot+6FR3WZcGKNnTGGFMZhtRdRhRXw5CFF5nhF7ZmVjRdFjRUOqXoVpGceUKMG0VFXjl9uBFveWHQdpBhmYclOdjFae0mbyMrgrOmUZ6kzOpmQFQYi8zII90U9m6cXlqdWmqvUWkLSOMdLONMNIwghfhLDvNlvtZxrqZh9QyT7liuRtyM+qNDxFrRSInuIEmJlPQxDtu+bVqCLcqIzRr+RPoGMPXeAa5I9RbF6JTuHYZSZ5u+HdhlhkXsodElDpck07KBjGRmHuUxC1fLX+VDTTRHKJtK1eAED5a45pAKx+bcRB0O8h4MsEjaYbdGFGeTh+B4VOucP6qxd8drCTZHMK9H42PvQM65zcRpFhYLysHjomAi4Ny6s0xgZuwFZHl+XfiYMpo17yK0jmUjiM6i1B2ophknsI1ia7M0U8rHxhP2ZrBoesuPJiqA/a9T903H9XKcwZp5memxSrq1HST6Yc75A2r8kPUsiqlbv1OLXKuay65DhLVeUq84dR9iwPBMC2fzDJNWbxOw4qzs1HbtDMsCAxP1Db4bXVGOD3xric/yJ3MWnVALOtKnfj6yty81WYHd4E8enB/OKdS6FBCb5cjKPrSG8iUNmCL3JNZjQjfvDknLf9+KWwH3UrYLZQaYb8QVINSoRG2q4V2GFbL/bBc6nUqD+BgkVFcDtPr+gFcYdBFdmmvx9cu7uPlLc2FEYuLTF/MF7Xh+uK+XNl8ce8RIJ37tcqgWW12aoVmtT0oBL1Oo9Ds1jqFXq1b7w163bDRHDzwvSMNDtrVblDrNwq1crdbCGolZX6jWagHlUo7qLcb/aD9ICtjYOUpfWS+APdqu7b/AQAA//8DAFBLAwQUAAYACAAAACEAIFJ/Xf0CAADCBwAADQAAAHhsL3N0eWxlcy54bWy0VW1v0zAQ/o7Ef7D8PctLm9JWSSbaLtIkQEgbEl+dxGmt+SVy3JGC+O+cnbTN2IAxRL/EPp+fe+6e8zW57ARH91S3TMkUhxcBRlSWqmJym+JPt7k3x6g1RFaEK0lTfKAtvsxev0pac+D0ZkepQQAh2xTvjGmWvt+WOypIe6EaKuGkVloQA1u99dtGU1K19pLgfhQEM18QJnGPsBTlc0AE0Xf7xiuVaIhhBePMHBwWRqJcXm+l0qTgQLULp6REXTjTEer0MYizPoojWKlVq2pzAbi+qmtW0sd0F/7CJ+UZCZBfhhTGfhA9yL3TL0Sa+preMysfzpJaSdOiUu2lSXEERG0JlndSfZG5PQKFB68sab+ie8LBEmI/S0rFlUYGpIPKOYskgvYea8JZoZl1q4lg/NCbI2twag9+gkHtrdG3PHo2WVJYr/8ey4VsISbj/FSBiU0WDFkCrWKoljls0LC+PTSQqoSu7ik7vz94bzU5hFH8/Aut4qyyLLZrV2C9LVKcu18QWJhiOGCyoh2tUjybOvQRYVtPR859IMdC6Qpe7FFnK2lvyhJOawOomm139mtUY2MoY6Crs6RiZKsk4Vai441hAbAl5fzGvurP9QPsrkZyL3JhroEezAcr7nEJvIZlj9dvLP4YrccewVph/h4WdfUJ/xm3of/HpE63EWkafrCtMHT6r7BCyPXpBH/GgooMWC5vyHRUzgfFPJUF2feV4g92PHJ4qUNqqNgzbph8opCAWXVnaVz7GDvqnGinKKBQRWuy5+b2dJji8/o9rdheQHEGr4/sXhkHkeLz+p3toHBme5F25l0Lzxm+aK9Zir9drd4sNld55M2D1dybTmjsLeLVxoun69Vmky+CKFh/Hw3cfxi37v8BmiWcLlsOQ1kPyQ7kb862FI82PX33koD2mPsimgVv4zDw8kkQetMZmXvz2ST28jiMNrPp6irO4xH3+IVjOfDDsB/wlny8NExQzuRRq6NCYyuIBNvfJOEflfDPf77ZDwAAAP//AwBQSwMEFAAGAAgAAAAhAMP/6oXRAAAAjwEAABQAAAB4bC9zaGFyZWRTdHJpbmdzLnhtbHTQwWrDMAwG4Ptg72C0c+skgzGG48IKPe6wdQ/gJVptiOU0UsL29nNgh+JuR31Cv4TM7isOasGJQ6IW6m0FCqlLfaBTC+/Hw+YRFIuj3g2JsIVvZNjZ2xvDLCrPErfgRcYnrbnzGB1v04iUO59pik5yOZ00jxO6nj2ixEE3VfWgowsEqkszSd7bgJopnGfc/0IN1nCwRuwxyICb2mixRq90yc3ffF/yi4tY2psPiyP2pb+6JZT2nD72pd39F3h165p4hWvkBer8UPsDAAD//wMAUEsDBBQABgAIAAAAIQA7bTJLwQAAAEIBAAAjAAAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHOEj8GKwjAURfcD/kN4e5PWhQxDUzciuFXnA2L62gbbl5D3FP17sxxlwOXlcM/lNpv7PKkbZg6RLNS6AoXkYxdosPB72i2/QbE46twUCS08kGHTLr6aA05OSonHkFgVC7GFUST9GMN+xNmxjgmpkD7m2UmJeTDJ+Ysb0Kyqam3yXwe0L0617yzkfVeDOj1SWf7sjn0fPG6jv85I8s+ESTmQYD6iSDnIRe3ygGJB63f2nmt9DgSmbczL8/YJAAD//wMAUEsDBBQABgAIAAAAIQCj1j1wNgEAAOQCAAAnAAAAeGwvcHJpbnRlclNldHRpbmdzL3ByaW50ZXJTZXR0aW5nczEuYmluzJK7SgNREIa/ObthN4YQ0cY7C6YSA4ksYmETYsBAIsFFSJHCItha28XK2k5S+AA+hLUPYBmwFfEBLJ3ZrJigpLDyDP/M7NyY85/t06fFCRU6nCkqJDQ5pUpNMwnH1PWrS6S5nmZrHCiqWhuRHh8ZE7rSyzAQ8owKcThACOg5Udtznuo68aT6z3rll07RmFOIOYYfx79KGked0N0EZc19KHa17k2RJNWmlc+/YZcGbfbnba33f2ZR/tP9YzZaxW2jRrm3w90S3K/BQGUnk8EMaY8swDXR+DbjU41xax15tflUT0jOqcmJkwBDyv4MQ3E4Klif/QXtEB6KcL4MF+vwrvZpdfJcYhPU9bLu0iU5HefEt4BzTvb4li0OdcdXr+wL3tRrm7uZTvgKDnW76YU+AQAA//8DAFBLAwQUAAYACAAAACEAVJMQakMBAABrAgAAEQAIAWRvY1Byb3BzL2NvcmUueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJJfS8MwFMXfBb9DyXubtnNDQtuByp4cCJsovoXkbg02f0jiun1703bW6nzwMTnn/nLOJcXyKJvoANYJrUqUJSmKQDHNhdqX6Hm7im9R5DxVnDZaQYlO4NCyur4qmCFMW3iy2oD1AlwUSMoRZkpUe28Ixo7VIKlLgkMFcaetpD4c7R4byt7pHnCepgsswVNOPcUdMDYjEZ2RnI1I82GbHsAZhgYkKO9wlmT42+vBSvfnQK9MnFL4kwmdznGnbM4GcXQfnRiNbdsm7ayPEfJn+HX9uOmrxkJ1u2KAqoIzwixQr221qcWBKldHG/B1gSdKt8WGOr8OC98J4Hen3+ZLQyD3RQY88ChEI0ORL+Vldv+wXaEqT/MsTvM4v9mmC5LlZDZ/697/Md9FHS7kOcX/iXOSTYlfgKrAF9+j+gQAAP//AwBQSwMEFAAGAAgAAAAhAGFJCRCJAQAAEQMAABAACAFkb2NQcm9wcy9hcHAueG1sIKIEASigAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnJJBb9swDIXvA/ofDN0bOd1QDIGsYkhX9LBhAZK2Z02mY6GyJIiskezXj7bR1Nl66o3ke3j6REndHDpf9JDRxVCJ5aIUBQQbaxf2lXjY3V1+FQWSCbXxMUAljoDiRl98UpscE2RygAVHBKxES5RWUqJtoTO4YDmw0sTcGeI272VsGmfhNtqXDgLJq7K8lnAgCDXUl+kUKKbEVU8fDa2jHfjwcXdMDKzVt5S8s4b4lvqnszlibKj4frDglZyLium2YF+yo6MulZy3amuNhzUH68Z4BCXfBuoezLC0jXEZtepp1YOlmAt0f3htV6L4bRAGnEr0JjsTiLEG29SMtU9IWT/F/IwtAKGSbJiGYzn3zmv3RS9HAxfnxiFgAmHhHHHnyAP+ajYm0zvEyznxyDDxTjjbgW86c843XplP+id7HbtkwpGFU/XDhWd8SLt4awhe13k+VNvWZKj5BU7rPg3UPW8y+yFk3Zqwh/rV878wPP7j9MP18npRfi75XWczJd/+sv4LAAD//wMAUEsBAi0AFAAGAAgAAAAhAEE3gs9uAQAABAUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAtVUwI/QAAABMAgAACwAAAAAAAAAAAAAAAACnAwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEARbo8GF0DAABaCAAADwAAAAAAAAAAAAAAAADMBgAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhAIE+lJfzAAAAugIAABoAAAAAAAAAAAAAAAAAVgoAAHhsL19yZWxzL3dvcmtib29rLnhtbC5yZWxzUEsBAi0AFAAGAAgAAAAhAAdhSeKLAgAARAYAABgAAAAAAAAAAAAAAAAAiQwAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQItABQABgAIAAAAIQDBFxC+TgcAAMYgAAATAAAAAAAAAAAAAAAAAEoPAAB4bC90aGVtZS90aGVtZTEueG1sUEsBAi0AFAAGAAgAAAAhACBSf139AgAAwgcAAA0AAAAAAAAAAAAAAAAAyRYAAHhsL3N0eWxlcy54bWxQSwECLQAUAAYACAAAACEAw//qhdEAAACPAQAAFAAAAAAAAAAAAAAAAADxGQAAeGwvc2hhcmVkU3RyaW5ncy54bWxQSwECLQAUAAYACAAAACEAO20yS8EAAABCAQAAIwAAAAAAAAAAAAAAAAD0GgAAeGwvd29ya3NoZWV0cy9fcmVscy9zaGVldDEueG1sLnJlbHNQSwECLQAUAAYACAAAACEAo9Y9cDYBAADkAgAAJwAAAAAAAAAAAAAAAAD2GwAAeGwvcHJpbnRlclNldHRpbmdzL3ByaW50ZXJTZXR0aW5nczEuYmluUEsBAi0AFAAGAAgAAAAhAFSTEGpDAQAAawIAABEAAAAAAAAAAAAAAAAAcR0AAGRvY1Byb3BzL2NvcmUueG1sUEsBAi0AFAAGAAgAAAAhAGFJCRCJAQAAEQMAABAAAAAAAAAAAAAAAAAA6x8AAGRvY1Byb3BzL2FwcC54bWxQSwUGAAAAAAwADAAmAwAAqiIAAAAA";
        // //var a = document.createElement('a');
        // a.href = mediaType+userInp;
        //a.href = mediaType+userInp;
        const downloadLink = document.createElement('a');
        //const fileName = 'sample.excel';

        downloadLink.href = mediaType + userInp;
        downloadLink.download = fileName;
        downloadLink.click();
    }

    ngOnDestroy() {
        // this.getYearSubscription.unsubscribe();
        //this.getStatusSubscription.unsubscribe();
    }

    onSubmit(status) {
        this.submitted.check = true;
        if (this.form.invalid || this.listupload.length == 0) {
            this._messageService.showWarningMessage("Thông báo", "Chưa nhập đủ trường bắt buộc!")
            return;
        }
        console.log(this.form);
        let name = this.form.value.name;
        let nam = this.form.value.year;

       // let capTao = 'DONVI';
       // if (this.listDonvi != undefined && this.listDonvi.length > 0) {
       //     capTao = "TCT";
       // }
        let listChiTiet = [];
        let listFile = this.listupload;
        let kehoach = { name: name, nam: nam, maTrangThai: status, maKeHoach: this.idParam };
        for (let i = 0; i < this.form.value.listNhiemVu.length; i++) {
            let chitiet1 = this.form.value.listNhiemVu[i];
            for (let j = 0; j < chitiet1.listNhiemVu_cap2.length; j++) {
                let chitiet2 = chitiet1.listNhiemVu_cap2[j];
                if (chitiet2.chiTiet == 0) {
                    listChiTiet.push(chitiet2);
                }
                if (chitiet2 != null && chitiet2.listNhiemVu_cap3 != undefined && chitiet2.listNhiemVu_cap3.length > 0) {
                    for (let k = 0; k < chitiet2.listNhiemVu_cap3.length; k++) {
                        let chitiet3 = chitiet2.listNhiemVu_cap3[k];
                        if (chitiet3.chiTiet == 0) {
                            listChiTiet.push(chitiet3);
                        }
                        if (chitiet3.listNhiemVu_cap4 != undefined && chitiet3.listNhiemVu_cap4.length > 0) {
                            for (let i = 0; i < chitiet3.listNhiemVu_cap4.length; i++) {
                                let chitiet4 = chitiet3.listNhiemVu_cap4[k];
                                if (chitiet4.chiTiet == 0) {
                                    listChiTiet.push(chitiet4);
                                }
                            }
                        }

                    }
                }
               

                // if (this.listDonvi != undefined && this.listDonvi.length > 0) {
                //     for (let k = 0; k < chitiet2.listNhiemVu_cap3.length; k++) {
                //         let itemChiTiet = chitiet2.listNhiemVu_cap3[k];

                //         if (itemChiTiet.listNhiemVu_cap4 != undefined && itemChiTiet.listNhiemVu_cap4.length > 0) {
                //             for (let i = 0; i < itemChiTiet.listNhiemVu_cap4.length; i++) {

                //                 listChiTiet.push(itemChiTiet.listNhiemVu_cap4[i]);
                //             }
                //         }
                //     }
                // } else {

                //     if (chitiet2.listNhiemVu_cap3 != undefined && chitiet2.listNhiemVu_cap3.length > 0) {
                //         for (let i = 0; i < chitiet2.listNhiemVu_cap3.length; i++) {

                //             listChiTiet.push(chitiet2.listNhiemVu_cap3[i]);
                //         }
                //     }
                // }


            }
        }
        if(status=='CHO_PHE_DUYET' && listChiTiet.length ==0){
            this._messageService.showWarningMessage("Thông báo", "Vui lòng thêm thông tin đăng ký định hướng.");
            return;
        }
   
        var token = localStorage.getItem("accessToken");
        this._serviceApi.execServiceLogin("404ABE65-3B92-448F-A8F0-9543503AE1E3", [{ "name": "LIST_FILE", "value": JSON.stringify(listFile) }, { "name": "LIST_KE_HOACH_CHI_TIET", "value": JSON.stringify(listChiTiet) }, { "name": "TOKEN_LINK", "value": "Bearer " + token }, { "name": "KE_HOACH", "value": JSON.stringify(kehoach) }]).subscribe((data) => {
            // this._messageService.showSuccessMessage("Thông báo", data.message);
            // this._router.navigateByUrl('nghiepvu/kehoach/dinhhuong');
            switch (data.status) {
                case 1:
                    this._messageService.showSuccessMessage("Thông báo", "Thành công");
                    if (this.screen) {
                        this._router.navigateByUrl(this.screen);
                    } else {
                        this._router.navigateByUrl('nghiepvu/kehoach/dinhhuong');
                    }
                    break;
                case 0:
                    this._messageService.showErrorMessage("Thông báo", "Không tìm thấy bản ghi");
                    break;
                case -1:
                    this._messageService.showErrorMessage("Thông báo", "Xảy ra lỗi khi thực hiện");
                    break;
            }
        })
    }
    listupload = []
    handleUpload(event) {
        for (var i = 0; i < event.target.files.length; i++) {
            const reader = new FileReader();
            let itemVal = event.target.files[i];
            reader.readAsDataURL(event.target.files[i]);
            reader.onload = () => {
                this.listupload.push({
                    fileName: itemVal.name,
                    base64: reader.result,
                    size: itemVal.size,
                    sovanban: "",
                    mafile: ""
                });
            };
        }
        event.target.value = null;

    }

    resetFileUploader() {
        this.fileUpload2.nativeElement.value = null;
    }
    dataFile = [];
    openAlertDialog(type) {
    
        let data = this.dialog.open(DOfficeComponent, {
            data: {
                type: type,
                linkApi: this.linkDoffice,
                maDv: this.user.ORGID,
            },
            width: '800px',
            panelClass: 'custom-PopupCbkh',
            position: {
                top: '100px',
            }
        });
        data.afterClosed().subscribe((data) => {
            //if (type == 'DOFFICE') {
            this.dataFile = this._dOfficeApi.execTimKiemTheoFile(this.linkDoffice, data.ID_VB).then(data=>{
                console.log(data.body.Data);
              
                //this.listDOffice =data.body.Data;
                if (this.dataFile != null && this.dataFile.length > 0) {

                    for (var i = 0; i < this.dataFile.length; i++) {
                        let dataBase64 = this._dOfficeApi.execFileBase64(this.linkDoffice, this.dataFile[i].ID_FILE, this.user.ORGID, this.dataFile[i].ID_VB);
                        this.listupload.push({
                            fileName: this.dataFile[i].TEN_FILE,
                            base64: dataBase64,
                            size: 0,
                            sovanban: data.KY_HIEU,
                            mafile: ""
                        })
                    }
                }
              });
           
        })
    }


    exportMau() {
        if (this.idParam != undefined && this.idParam != null) {
            this._serviceApi.execServiceLogin("FC95C3F7-942F-4C7E-88D7-46E12BFE9185", [{ "name": "MA_KE_HOACH", "value": this.idParam }]).subscribe((data) => {
                this.downloadTempExcel(data.data, "DANH_SACH_DANG_KY_DINH_HUONG.docx");

           })
        } else {
            this._messageService.showWarningMessage("Thông báo", "Chức năng này không được sử dụng.");
        }
    }

    downLoadFile(item) {
        // var ext = item.fileName.substring(item.fileName.lastIndexOf(".") + 1);
        // if(ext =='pdf'){
        //         window.open(url, "_blank");
        // }   
        if (item.base64 != undefined && item.base64 != '') {
            let link = item.base64.split(',');
            let url = '';
            if (link.length > 1) {
                url = link[1];
            } else {
                url = link[0];
            }
            this.downloadAll(url, item.fileName);
        } else {
            var token = localStorage.getItem('accessToken');
            this._serviceApi
                .execServiceLogin('2269B72D-1A44-4DBB-8699-AF9EE6878F89', [
                    {name: 'DUONG_DAN', value: item.duongdan},
                    {name: 'TOKEN_LINK', value: 'Bearer ' + token},
                ])
                .subscribe((data) => {
                });
        }
    }

   async downloadAll(base64String, fileName){
    let typeFile =  await this.detectMimeType(base64String, fileName);
    let mediaType = `data:${typeFile};base64,`;
    const downloadLink = document.createElement('a');
        downloadLink.href = mediaType + base64String;
        downloadLink.download = fileName;
        if(typeFile == 'application/pdf'){
        this.openAlertDialogViewFile(downloadLink.href)// popup view file pdf
        }else{
            downloadLink.click();
        }
    }

   async detectMimeType(base64String, fileName) {
        var ext = fileName.substring(fileName.lastIndexOf(".") + 1);
        if (ext === undefined || ext === null || ext === "") ext = "bin";
        ext = ext.toLowerCase();
        const signatures = {
          JVBERi0: "application/pdf",
          R0lGODdh: "image/gif",
          R0lGODlh: "image/gif",
          iVBORw0KGgo: "image/png",
          TU0AK: "image/tiff",
          "/9j/": "image/jpg",
          UEs: "application/vnd.openxmlformats-officedocument.",
          PK: "application/zip",
        };
        for (var s in signatures) {
          if (base64String.indexOf(s) === 0) {
            var x = signatures[s];
            // if an office file format
            if (ext.length > 3 && ext.substring(0, 3) === "ppt") {
              x += "presentationml.presentation";
            } else if (ext.length > 3 && ext.substring(0, 3) === "xls") {
              x += "spreadsheetml.sheet";
            } else if (ext.length > 3 && ext.substring(0, 3) === "doc") {
              x += "wordprocessingml.document";
            }
            // return
            return x;
          }
        }
        // if we are here we can only go off the extensions
        const extensions = {
          xls: "application/vnd.ms-excel",
          ppt: "application/vnd.ms-powerpoint",
          doc: "application/msword",
          xml: "text/xml",
          mpeg: "audio/mpeg",
          mpg: "audio/mpeg",
          txt: "text/plain",
        };
        for (var e in extensions) {
          if (ext.indexOf(e) === 0) {
            var xx = extensions[e];
            return xx;
          }
        }
        // if we are here – not sure what type this is
        return "unknown";
      }

    deleteItemFile(items) {
        if (items.mafile != undefined && items.mafile != '') {
            this.listupload = this.listupload.filter(item => item.mafile != items.mafile);
        } else {
            this.listupload = this.listupload.filter(item => item.fileName != items.fileName);
        }
        if (items.mafile != null && items.mafile != '') {
            this.listFileDelete.push(items);
            // this._serviceApi.execServiceLogin("83C28EE1-6A5A-4ADA-B866-287EBAC8B5D5", [{"name":"MA_FILE","value":items.mafile}]).subscribe((data) => {

            // })
        }
    }

    async openAlertDialogDoffice(type, item?: any) {
        let data = this.dialog.open(DOfficeComponent, {
            data: {
                type: type,
                linkApi: this.linkDoffice,
                maDv: this.user.ORGID,
                message: 'HelloWorld',
                buttonText: {
                    cancel: 'Done',
                },
            },
            width: '800px',
            panelClass: 'custom-PopupCbkh',
            position: {
                top: '100px',
            },
        });

         data.afterClosed().subscribe((data) => {
           let kyHieu =data.data.KY_HIEU;
           let ngayVB =data.data.NGAY_VB;
           //item.get("sovanban").setValue(kyHieu);
           //item.get("ngayVanBan").setValue(ngayVB);
            if (type == 'DOffice') {
                  this._dOfficeApi.execTimKiemTheoFile(this.linkDoffice, data.data.ID_VB).then(data=>{
                this.dataFile = data.body.Data;
                console.log("thong tin file");
                console.log(data);
                if (this.dataFile != null && this.dataFile.length > 0) {
                   for (var i = 0; i < this.dataFile.length; i++) {
                    this.getFileFromDoffice(item, this.dataFile[i].ID_FILE, this.user.ORGID, this.dataFile[i].ID_VB,
                         this.dataFile[i].TEN_FILE, this.dataFile[i].KY_HIEU);
                //         let dataFile =  this.dataFile[i];
                //         setTimeout(() => {
                            
                     
                   
                // }, 1000);
                //     }
                }
            }
            }); 
            }
        });
    }
    async getFileFromDoffice(item,idFile,orgId,idVB,tenFile,kyHieu){
        this._dOfficeApi.execFileBase64(this.linkDoffice, idFile, orgId, idVB).then(data=>{
            console.log("file base64");
            var base64str = data.body;
            var decoded = atob(base64str);
             this.listupload.push({
                fileName: tenFile,
                base64: base64str,
                size: decoded.length,
                sovanban: kyHieu,
                mafile: ""
             })
            });
            
    }


    async openAlertDialogViewFile(base64) {
        let data = this.dialog.open(ViewFileComponent, {
            data: {
                file: base64,
            },
            width: '1000px',
            panelClass: 'custom-Popupviewfile',
            position: {
                top: '1px',
            },
        });
    }

    // addListDocChildView(tenFile,base64str,decoded,kyHieu) {
    //     return this._formBuilder.group({
    //         fileName: tenFile,
    //         base64: base64str,
    //         size: decoded.length,
    //         sovanban: kyHieu,
    //         mafile: ""
    //     });
    // }
 

}
